[build]
  command = "DATABASE_URL=\"$NETLIFY_DATABASE_URL\" bun run prisma:push && bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]
